# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ui_files/AlphaWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AlphaWindow(object):
    def setupUi(self, AlphaWindow):
        AlphaWindow.setObjectName("AlphaWindow")
        AlphaWindow.resize(550, 95)
        self.centralwidget = QtWidgets.QWidget(AlphaWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 531, 41))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.AlphaSlider = QtWidgets.QSlider(self.verticalLayoutWidget)
        self.AlphaSlider.setMinimum(0)
        self.AlphaSlider.setMaximum(100)
        self.AlphaSlider.setSingleStep(1)
        self.AlphaSlider.setProperty("value", 1)
        self.AlphaSlider.setSliderPosition(1)
        self.AlphaSlider.setOrientation(QtCore.Qt.Horizontal)
        self.AlphaSlider.setObjectName("AlphaSlider")
        self.verticalLayout.addWidget(self.AlphaSlider)
        AlphaWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(AlphaWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 550, 21))
        self.menubar.setObjectName("menubar")
        AlphaWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(AlphaWindow)
        self.statusbar.setObjectName("statusbar")
        AlphaWindow.setStatusBar(self.statusbar)

        self.retranslateUi(AlphaWindow)
        QtCore.QMetaObject.connectSlotsByName(AlphaWindow)

    def retranslateUi(self, AlphaWindow):
        _translate = QtCore.QCoreApplication.translate
        AlphaWindow.setWindowTitle(_translate("AlphaWindow", "Прозрачность"))
