# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ui_files/ColorWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ColorWindow(object):
    def setupUi(self, ColorWindow):
        ColorWindow.setObjectName("ColorWindow")
        ColorWindow.resize(300, 260)
        self.centralwidget = QtWidgets.QWidget(ColorWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 281, 201))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.RedButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.RedButton.setObjectName("RedButton")
        self.verticalLayout.addWidget(self.RedButton)
        self.GreenButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.GreenButton.setObjectName("GreenButton")
        self.verticalLayout.addWidget(self.GreenButton)
        self.BlueButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.BlueButton.setObjectName("BlueButton")
        self.verticalLayout.addWidget(self.BlueButton)
        self.AllButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.AllButton.setObjectName("AllButton")
        self.verticalLayout.addWidget(self.AllButton)
        ColorWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ColorWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 300, 21))
        self.menubar.setObjectName("menubar")
        ColorWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ColorWindow)
        self.statusbar.setObjectName("statusbar")
        ColorWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ColorWindow)
        QtCore.QMetaObject.connectSlotsByName(ColorWindow)

    def retranslateUi(self, ColorWindow):
        _translate = QtCore.QCoreApplication.translate
        ColorWindow.setWindowTitle(_translate("ColorWindow", "Цветовой канал"))
        self.RedButton.setText(_translate("ColorWindow", "Красный"))
        self.GreenButton.setText(_translate("ColorWindow", "Зеленый"))
        self.BlueButton.setText(_translate("ColorWindow", "Синий"))
        self.AllButton.setText(_translate("ColorWindow", "Все"))
