# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ui_files/dialog_wh.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_wh(object):
    def setupUi(self, Dialog_wh):
        Dialog_wh.setObjectName("Dialog_wh")
        Dialog_wh.resize(400, 210)
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog_wh)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 19, 381, 141))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.spinBox = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.spinBox.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(1500)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout.addWidget(self.spinBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.spinBox_2 = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.spinBox_2.setMinimum(1)
        self.spinBox_2.setMaximum(1500)
        self.spinBox_2.setObjectName("spinBox_2")
        self.horizontalLayout_2.addWidget(self.spinBox_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.pushButton = QtWidgets.QPushButton(Dialog_wh)
        self.pushButton.setGeometry(QtCore.QRect(300, 170, 91, 31))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Dialog_wh)
        QtCore.QMetaObject.connectSlotsByName(Dialog_wh)

    def retranslateUi(self, Dialog_wh):
        _translate = QtCore.QCoreApplication.translate
        Dialog_wh.setWindowTitle(_translate("Dialog_wh", "Создать"))
        self.label.setText(_translate("Dialog_wh", "<html><head/><body><p><span style=\" font-size:18pt;\">Введите ширину и высоту:</span></p></body></html>"))
        self.label_2.setText(_translate("Dialog_wh", "<html><head/><body><p><span style=\" font-size:14pt;\">Ширина</span></p></body></html>"))
        self.label_3.setText(_translate("Dialog_wh", "<html><head/><body><p><span style=\" font-size:14pt;\">Высота</span></p></body></html>"))
        self.pushButton.setText(_translate("Dialog_wh", "ОК"))
