# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ui_files/DrawWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DrawWindow(object):
    def setupUi(self, DrawWindow):
        DrawWindow.setObjectName("DrawWindow")
        DrawWindow.resize(260, 200)
        self.centralwidget = QtWidgets.QWidget(DrawWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 241, 141))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.LineButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.LineButton.setObjectName("LineButton")
        self.verticalLayout.addWidget(self.LineButton)
        self.SquareButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.SquareButton.setObjectName("SquareButton")
        self.verticalLayout.addWidget(self.SquareButton)
        self.CircleButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.CircleButton.setObjectName("CircleButton")
        self.verticalLayout.addWidget(self.CircleButton)
        self.PolygonButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.PolygonButton.setObjectName("PolygonButton")
        self.verticalLayout.addWidget(self.PolygonButton)
        DrawWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(DrawWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 260, 21))
        self.menubar.setObjectName("menubar")
        DrawWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(DrawWindow)
        self.statusbar.setObjectName("statusbar")
        DrawWindow.setStatusBar(self.statusbar)

        self.retranslateUi(DrawWindow)
        QtCore.QMetaObject.connectSlotsByName(DrawWindow)

    def retranslateUi(self, DrawWindow):
        _translate = QtCore.QCoreApplication.translate
        DrawWindow.setWindowTitle(_translate("DrawWindow", "Нарисовать"))
        self.LineButton.setText(_translate("DrawWindow", "линия"))
        self.SquareButton.setText(_translate("DrawWindow", "квадрат"))
        self.CircleButton.setText(_translate("DrawWindow", "круг"))
        self.PolygonButton.setText(_translate("DrawWindow", "многоугольник"))
