# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ui_files/ReflectWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ReflectWindow(object):
    def setupUi(self, ReflectWindow):
        ReflectWindow.setObjectName("ReflectWindow")
        ReflectWindow.resize(300, 120)
        self.centralwidget = QtWidgets.QWidget(ReflectWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 281, 91))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.VerticalButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.VerticalButton.setObjectName("VerticalButton")
        self.verticalLayout.addWidget(self.VerticalButton)
        self.HorizontalButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.HorizontalButton.setObjectName("HorizontalButton")
        self.verticalLayout.addWidget(self.HorizontalButton)
        ReflectWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ReflectWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 300, 21))
        self.menubar.setObjectName("menubar")
        ReflectWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ReflectWindow)
        self.statusbar.setObjectName("statusbar")
        ReflectWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ReflectWindow)
        QtCore.QMetaObject.connectSlotsByName(ReflectWindow)

    def retranslateUi(self, ReflectWindow):
        _translate = QtCore.QCoreApplication.translate
        ReflectWindow.setWindowTitle(_translate("ReflectWindow", "Отразить"))
        self.VerticalButton.setText(_translate("ReflectWindow", "вертикально"))
        self.HorizontalButton.setText(_translate("ReflectWindow", "горизонтально"))
