# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ui_files/RotateWidow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RotateWindow(object):
    def setupUi(self, RotateWindow):
        RotateWindow.setObjectName("RotateWindow")
        RotateWindow.resize(335, 150)
        self.centralwidget = QtWidgets.QWidget(RotateWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 321, 91))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.RightButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.RightButton.setObjectName("RightButton")
        self.verticalLayout.addWidget(self.RightButton)
        self.LeftButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.LeftButton.setObjectName("LeftButton")
        self.verticalLayout.addWidget(self.LeftButton)
        RotateWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(RotateWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 335, 21))
        self.menubar.setObjectName("menubar")
        RotateWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(RotateWindow)
        self.statusbar.setObjectName("statusbar")
        RotateWindow.setStatusBar(self.statusbar)

        self.retranslateUi(RotateWindow)
        QtCore.QMetaObject.connectSlotsByName(RotateWindow)

    def retranslateUi(self, RotateWindow):
        _translate = QtCore.QCoreApplication.translate
        RotateWindow.setWindowTitle(_translate("RotateWindow", "Повернуть"))
        self.RightButton.setText(_translate("RotateWindow", "По часовой"))
        self.LeftButton.setText(_translate("RotateWindow", "Против часовой"))
