# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ui_files/SizeDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SizeDialog(object):
    def setupUi(self, SizeDialog):
        SizeDialog.setObjectName("SizeDialog")
        SizeDialog.resize(410, 210)
        self.verticalLayoutWidget = QtWidgets.QWidget(SizeDialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 391, 141))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.WspinBox = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.WspinBox.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.WspinBox.setMinimum(1)
        self.WspinBox.setMaximum(1500)
        self.WspinBox.setObjectName("WspinBox")
        self.horizontalLayout.addWidget(self.WspinBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.HspinBox = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.HspinBox.setMinimum(1)
        self.HspinBox.setMaximum(1500)
        self.HspinBox.setObjectName("HspinBox")
        self.horizontalLayout_2.addWidget(self.HspinBox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.pushButton = QtWidgets.QPushButton(SizeDialog)
        self.pushButton.setGeometry(QtCore.QRect(310, 170, 91, 31))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(SizeDialog)
        QtCore.QMetaObject.connectSlotsByName(SizeDialog)

    def retranslateUi(self, SizeDialog):
        _translate = QtCore.QCoreApplication.translate
        SizeDialog.setWindowTitle(_translate("SizeDialog", "Укажите размеры"))
        self.label.setText(_translate("SizeDialog", "<html><head/><body><p><span style=\" font-size:18pt;\">Введите ширину и высоту:</span></p></body></html>"))
        self.label_2.setText(_translate("SizeDialog", "<html><head/><body><p><span style=\" font-size:14pt;\">Ширина</span></p></body></html>"))
        self.label_3.setText(_translate("SizeDialog", "<html><head/><body><p><span style=\" font-size:14pt;\">Высота</span></p></body></html>"))
        self.pushButton.setText(_translate("SizeDialog", "ОК"))
